apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-pod-autoscaler.fullname" . }}
  labels:
    {{- include "smart-pod-autoscaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: metrics
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: webhook-server
  selector:
    {{- include "smart-pod-autoscaler.selectorLabels" . | nindent 4 }}
