name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Set up Kind
      uses: helm/kind-action@v1.10.0
      with:
        config: test/kind-config.yaml
        cluster_name: smart-pod-autoscaler-test-e2e

    - name: Run E2E Tests
      run: |
        make test-e2e IMG=smart-pod-autoscaler:latest
